url: https://alehvasilyeu.github.io/hannas-cv
baseurl:

# Site settings
title: Hanna's UX Design Studio
email: annfili611@gmail.com
description: "Hi, I’m Hanna, your full service UI/UX designer, who creates creative and effective apps."


# Team names, titles and social links
people:
- name: Hanna Filipenka
  pic: profile
  position: UI/UX Designer
  social:
    - title: linkedin
      url: #
    - title: envelope
      url: mailto:test@example.com
    # - title: whatsapp
    #   url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  # - line: 3481 Melrose Place
  # - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty